# Generated by Django 4.2.3 on 2023-07-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_food_picture_alter_food_name'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='food',
            field=models.ManyToManyField(to='food.food'),
        ),
    ]
