# Generated by Django 4.2.3 on 2023-08-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_remove_foodmaterialmembership_food_and_more'),
        ('category', '0003_alter_category_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='food',
            field=models.ManyToManyField(default=None, to='food.food'),
        ),
    ]
