# Generated by Django 4.2.3 on 2023-08-04 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_alter_category_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='food',
        ),
    ]
