# Generated by Django 4.2.3 on 2023-07-31 15:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chef',
            name='rank',
        ),
        migrations.AlterField(
            model_name='chef',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.RegexValidator(message='email is not valid', regex='^\\S+@\\S+\\.\\S+$')]),
        ),
        migrations.AlterField(
            model_name='chef',
            name='password',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='password is not good', regex='^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{8,}$')]),
        ),
    ]
