# Generated by Django 4.2.3 on 2023-07-31 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_food_picture_alter_food_name'),
        ('chef', '0002_remove_chef_rank_alter_chef_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='food',
            field=models.ManyToManyField(to='food.food'),
        ),
        migrations.CreateModel(
            name='ChefFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.food')),
            ],
        ),
    ]
