# Generated by Django 4.2.3 on 2023-07-31 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0004_delete_cheffood'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='password2',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
