# Generated by Django 4.2.3 on 2023-07-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('raw_material', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('recipe', models.TextField()),
                ('ranking', models.CharField(blank=True, choices=[('1', 'very_bad'), ('2', 'bad'), ('3', 'usual'), ('4', 'yummy'), ('5', 'delicious')], max_length=10, null=True)),
                ('foods_category', models.ManyToManyField(to='category.category')),
                ('raw_materials', models.ManyToManyField(to='raw_material.rawmaterial')),
            ],
        ),
    ]
