# Generated by Django 4.2.3 on 2023-07-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_food'),
        ('food', '0003_food_picture_alter_food_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='foods_category',
            field=models.ManyToManyField(related_name='category_of_food', to='category.category'),
        ),
    ]
