# Generated by Django 4.2.3 on 2023-07-31 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0001_initial'),
        ('food', '0004_alter_food_foods_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='raw_materials',
            field=models.ManyToManyField(related_name='material_of_food', to='raw_material.rawmaterial'),
        ),
    ]
