# Generated by Django 4.2.3 on 2023-07-31 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_food_chefs_of_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodmaterialmembership',
            name='food',
        ),
        migrations.RemoveField(
            model_name='foodmaterialmembership',
            name='raw_material',
        ),
        migrations.DeleteModel(
            name='FoodCategoryMemberShip',
        ),
        migrations.DeleteModel(
            name='FoodMaterialMemberShip',
        ),
    ]
